/**
 * Channel Registry — Single source of truth for relay channels.
 *
 * Replaces the "4 registries" problem: RELAY_CHANNELS, PHASE4_CHANNEL_KEYS,
 * setupRelayPush wiring, and DEFAULT_PANELS channel declarations.
 *
 * @see docs/plans/2026-03-09-frontend-refactor.md
 */

import type { MapLayers } from '@/types';

export type DataDomain =
  | 'news'
  | 'markets'
  | 'economic'
  | 'intelligence'
  | 'geo'
  | 'military'
  | 'infrastructure'
  | 'ai'
  | 'config';

export interface ChannelDefinition {
  key: string;
  redisKey: string;
  panels: string[];
  domain: DataDomain;
  staleAfterMs: number;
  timeoutMs: number;
  required: boolean;
  mapLayers?: (keyof MapLayers)[];
}

/** All relay channels with their Redis keys, panel mappings, and metadata. */
export const CHANNEL_REGISTRY: Record<string, ChannelDefinition> = {
  markets: {
    key: 'markets',
    redisKey: 'market:dashboard:v1',
    panels: ['markets', 'heatmap'],
    domain: 'markets',
    staleAfterMs: 5 * 60_000,
    timeoutMs: 30_000,
    required: true,
  },
  predictions: {
    key: 'predictions',
    redisKey: 'relay:predictions:v1',
    panels: ['polymarket'],
    domain: 'markets',
    staleAfterMs: 5 * 60_000,
    timeoutMs: 30_000,
    required: false,
  },
  fred: {
    key: 'fred',
    redisKey: 'relay:fred:v1',
    panels: ['commodities', 'economic'],
    domain: 'economic',
    staleAfterMs: 15 * 60_000,
    timeoutMs: 30_000,
    required: true,
  },
  oil: {
    key: 'oil',
    redisKey: 'relay:oil:v1',
    panels: ['commodities'],
    domain: 'economic',
    staleAfterMs: 5 * 60_000,
    timeoutMs: 30_000,
    required: true,
  },
  bis: {
    key: 'bis',
    redisKey: 'relay:bis:v1',
    panels: ['commodities', 'economic'],
    domain: 'economic',
    staleAfterMs: 15 * 60_000,
    timeoutMs: 30_000,
    required: true,
  },
  flights: {
    key: 'flights',
    redisKey: 'relay:flights:v1',
    panels: ['map'],
    domain: 'infrastructure',
    staleAfterMs: 5 * 60_000,
    timeoutMs: 30_000,
    required: false,
    mapLayers: ['flights'],
  },
  weather: {
    key: 'weather',
    redisKey: 'relay:weather:v1',
    panels: ['map'],
    domain: 'geo',
    staleAfterMs: 5 * 60_000,
    timeoutMs: 30_000,
    required: false,
    mapLayers: ['weather'],
  },
  natural: {
    key: 'natural',
    redisKey: 'relay:natural:v1',
    panels: ['map'],
    domain: 'geo',
    staleAfterMs: 10 * 60_000,
    timeoutMs: 30_000,
    required: false,
    mapLayers: ['natural'],
  },
  eonet: {
    key: 'eonet',
    redisKey: 'relay:eonet:v1',
    panels: ['map'],
    domain: 'geo',
    staleAfterMs: 10 * 60_000,
    timeoutMs: 30_000,
    required: false,
    mapLayers: ['natural'],
  },
  gdacs: {
    key: 'gdacs',
    redisKey: 'relay:gdacs:v1',
    panels: ['map'],
    domain: 'geo',
    staleAfterMs: 10 * 60_000,
    timeoutMs: 30_000,
    required: false,
    mapLayers: ['natural'],
  },
  'gps-interference': {
    key: 'gps-interference',
    redisKey: 'relay:gps-interference:v1',
    panels: ['map'],
    domain: 'infrastructure',
    staleAfterMs: 10 * 60_000,
    timeoutMs: 30_000,
    required: false,
    mapLayers: ['gpsJamming'],
  },
  cables: {
    key: 'cables',
    redisKey: 'relay:cables:v1',
    panels: ['cascade', 'map'],
    domain: 'infrastructure',
    staleAfterMs: 10 * 60_000,
    timeoutMs: 30_000,
    required: false,
    mapLayers: ['cables'],
  },
  cyber: {
    key: 'cyber',
    redisKey: 'relay:cyber:v1',
    panels: ['cascade', 'map'],
    domain: 'infrastructure',
    staleAfterMs: 10 * 60_000,
    timeoutMs: 30_000,
    required: false,
    mapLayers: ['cyberThreats'],
  },
  climate: {
    key: 'climate',
    redisKey: 'relay:climate:v1',
    panels: ['climate', 'map'],
    domain: 'geo',
    staleAfterMs: 15 * 60_000,
    timeoutMs: 30_000,
    required: false,
    mapLayers: ['climate'],
  },
  conflict: {
    key: 'conflict',
    redisKey: 'relay:conflict:v1',
    panels: ['cii', 'intel', 'map'],
    domain: 'intelligence',
    staleAfterMs: 10 * 60_000,
    timeoutMs: 30_000,
    required: true,
    mapLayers: ['conflicts'],
  },
  'ucdp-events': {
    key: 'ucdp-events',
    redisKey: 'conflict:ucdp-events:v1',
    panels: ['ucdp-events', 'map'],
    domain: 'intelligence',
    staleAfterMs: 10 * 60_000,
    timeoutMs: 30_000,
    required: false,
    mapLayers: ['ucdpEvents'],
  },
  telegram: {
    key: 'telegram',
    redisKey: 'relay:telegram:v1',
    panels: ['telegram-intel', 'intel'],
    domain: 'intelligence',
    staleAfterMs: 5 * 60_000,
    timeoutMs: 30_000,
    required: false,
  },
  oref: {
    key: 'oref',
    redisKey: 'relay:oref:v1',
    panels: ['oref-sirens', 'map'],
    domain: 'intelligence',
    staleAfterMs: 1 * 60_000,
    timeoutMs: 30_000,
    required: false,
    mapLayers: ['conflicts'],
  },
  ais: {
    key: 'ais',
    redisKey: 'relay:ais-snapshot:v1',
    panels: ['map'],
    domain: 'infrastructure',
    staleAfterMs: 5 * 60_000,
    timeoutMs: 30_000,
    required: false,
    mapLayers: ['ais'],
  },
  intelligence: {
    key: 'intelligence',
    redisKey: 'ai:digest:global:v1',
    panels: ['intel', 'gdelt-intel', 'global-digest'],
    domain: 'intelligence',
    staleAfterMs: 15 * 60_000,
    timeoutMs: 30_000,
    required: true,
  },
  trade: {
    key: 'trade',
    redisKey: 'relay:trade:v1',
    panels: ['commodities', 'trade-policy'],
    domain: 'economic',
    staleAfterMs: 15 * 60_000,
    timeoutMs: 30_000,
    required: true,
  },
  'supply-chain': {
    key: 'supply-chain',
    redisKey: 'supply_chain:chokepoints:v1',
    panels: ['commodities', 'supply-chain', 'cascade'],
    domain: 'economic',
    staleAfterMs: 15 * 60_000,
    timeoutMs: 30_000,
    required: true,
  },
  giving: {
    key: 'giving',
    redisKey: 'giving:summary:v1',
    panels: ['giving'],
    domain: 'economic',
    staleAfterMs: 15 * 60_000,
    timeoutMs: 30_000,
    required: false,
  },
  spending: {
    key: 'spending',
    redisKey: 'relay:spending:v1',
    panels: ['map'],
    domain: 'economic',
    staleAfterMs: 15 * 60_000,
    timeoutMs: 30_000,
    required: false,
    mapLayers: ['economic'],
  },
  'gulf-quotes': {
    key: 'gulf-quotes',
    redisKey: 'relay:gulf-quotes:v1',
    panels: ['gulf-economies'],
    domain: 'markets',
    staleAfterMs: 5 * 60_000,
    timeoutMs: 30_000,
    required: false,
  },
  'tech-events': {
    key: 'tech-events',
    redisKey: 'relay:tech-events:v1',
    panels: ['events'],
    domain: 'infrastructure',
    staleAfterMs: 10 * 60_000,
    timeoutMs: 30_000,
    required: false,
    mapLayers: ['techEvents'],
  },
  'strategic-posture': {
    key: 'strategic-posture',
    redisKey: 'theater-posture:sebuf:v1',
    panels: ['strategic-posture'],
    domain: 'intelligence',
    staleAfterMs: 15 * 60_000,
    timeoutMs: 30_000,
    required: true,
  },
  'strategic-risk': {
    key: 'strategic-risk',
    redisKey: 'risk:scores:sebuf:v1',
    panels: ['strategic-risk', 'cii'],
    domain: 'intelligence',
    staleAfterMs: 15 * 60_000,
    timeoutMs: 30_000,
    required: true,
  },
  stablecoins: {
    key: 'stablecoins',
    redisKey: 'relay:stablecoins:v1',
    panels: ['stablecoins'],
    domain: 'markets',
    staleAfterMs: 5 * 60_000,
    timeoutMs: 30_000,
    required: false,
  },
  'etf-flows': {
    key: 'etf-flows',
    redisKey: 'relay:etf-flows:v1',
    panels: ['etf-flows'],
    domain: 'markets',
    staleAfterMs: 5 * 60_000,
    timeoutMs: 30_000,
    required: false,
  },
  'macro-signals': {
    key: 'macro-signals',
    redisKey: 'economic:macro-signals:v1',
    panels: ['macro-signals'],
    domain: 'markets',
    staleAfterMs: 5 * 60_000,
    timeoutMs: 30_000,
    required: false,
  },
  'service-status': {
    key: 'service-status',
    redisKey: 'relay:service-status:v1',
    panels: ['service-status'],
    domain: 'infrastructure',
    staleAfterMs: 2 * 60_000,
    timeoutMs: 30_000,
    required: false,
  },
  'config:news-sources': {
    key: 'config:news-sources',
    redisKey: 'relay:config:news-sources',
    panels: [],
    domain: 'config',
    staleAfterMs: 5 * 60_000,
    timeoutMs: 30_000,
    required: false,
  },
  'config:feature-flags': {
    key: 'config:feature-flags',
    redisKey: 'relay:config:feature-flags',
    panels: [],
    domain: 'config',
    staleAfterMs: 5 * 60_000,
    timeoutMs: 30_000,
    required: false,
  },
  'iran-events': {
    key: 'iran-events',
    redisKey: 'conflict:iran-events:v1',
    panels: ['map'],
    domain: 'intelligence',
    staleAfterMs: 5 * 60_000,
    timeoutMs: 30_000,
    required: false,
    mapLayers: ['iranAttacks'],
  },
  'ai:intel-digest': {
    key: 'ai:intel-digest',
    redisKey: 'ai:digest:global:v1',
    panels: ['global-digest'],
    domain: 'ai',
    staleAfterMs: 15 * 60_000,
    timeoutMs: 30_000,
    required: false,
  },
  'ai:panel-summary': {
    key: 'ai:panel-summary',
    redisKey: 'ai:panel-summary:v1',
    panels: ['insights'],
    domain: 'ai',
    staleAfterMs: 15 * 60_000,
    timeoutMs: 30_000,
    required: false,
  },
  'ai:article-summaries': {
    key: 'ai:article-summaries',
    redisKey: 'ai:article-summaries:v1',
    panels: [],
    domain: 'ai',
    staleAfterMs: 15 * 60_000,
    timeoutMs: 30_000,
    required: false,
  },
  'ai:classifications': {
    key: 'ai:classifications',
    redisKey: 'ai:classifications:v1',
    panels: [],
    domain: 'ai',
    staleAfterMs: 15 * 60_000,
    timeoutMs: 30_000,
    required: false,
  },
  'ai:country-briefs': {
    key: 'ai:country-briefs',
    redisKey: 'ai:country-briefs:v1',
    panels: ['cii'],
    domain: 'ai',
    staleAfterMs: 15 * 60_000,
    timeoutMs: 30_000,
    required: false,
  },
  'ai:posture-analysis': {
    key: 'ai:posture-analysis',
    redisKey: 'ai:posture-analysis:v1',
    panels: ['strategic-posture'],
    domain: 'ai',
    staleAfterMs: 15 * 60_000,
    timeoutMs: 30_000,
    required: false,
  },
  'ai:instability-analysis': {
    key: 'ai:instability-analysis',
    redisKey: 'ai:instability-analysis:v1',
    panels: ['strategic-risk'],
    domain: 'ai',
    staleAfterMs: 15 * 60_000,
    timeoutMs: 30_000,
    required: false,
  },
  'ai:risk-overview': {
    key: 'ai:risk-overview',
    redisKey: 'ai:risk-overview:v1',
    panels: ['strategic-risk'],
    domain: 'ai',
    staleAfterMs: 15 * 60_000,
    timeoutMs: 30_000,
    required: false,
  },
};

/** Channel keys for bootstrap and WebSocket subscription. Replaces RELAY_CHANNELS. */
export const RELAY_CHANNELS = Object.keys(CHANNEL_REGISTRY);

/** Map channel key → Redis key. Replaces PHASE4_CHANNEL_KEYS. */
export const REDIS_KEY_MAP = Object.fromEntries(
  Object.entries(CHANNEL_REGISTRY).map(([k, v]) => [k, v.redisKey])
);
