INSERT INTO wm_admin.service_config (service_key, cron_schedule, redis_key, ttl_seconds, fetch_type, description, settings)
VALUES
  ('markets',           '*/5 * * * *',         'market:dashboard:v1',              300,   'custom', 'Market dashboard data', '{}'),
  ('stablecoins',       '*/5 * * * *',         'relay:stablecoins:v1',             300,   'custom', 'Stablecoin data', '{}'),
  ('etf-flows',         '*/5 * * * *',         'relay:etf-flows:v1',               300,   'custom', 'ETF flow data', '{}'),
  ('macro-signals',     '3-59/5 * * * *',      'economic:macro-signals:v1',        300,   'custom', 'Macro economic signals', '{}'),
  ('strategic-risk',    '*/5 * * * *',         'risk:scores:sebuf:v1',             300,   'custom', 'Strategic risk scores', '{}'),
  ('predictions',       '1-59/5 * * * *',      'relay:predictions:v1',             300,   'custom', 'Predictions data', '{}'),
  ('news:full',         '*/5 * * * *',         'news:digest:v1:full:en',           300,   'custom', 'Full news digest', '{}'),
  ('news:tech',         '1-59/5 * * * *',      'news:digest:v1:tech:en',           300,   'custom', 'Tech news digest', '{}'),
  ('news:finance',      '2-59/5 * * * *',      'news:digest:v1:finance:en',        300,   'custom', 'Finance news digest', '{}'),
  ('news:happy',        '3-59/5 * * * *',      'news:digest:v1:happy:en',          300,   'custom', 'Happy news digest', '{}'),
  ('supply-chain',      '2-59/10 * * * *',     'supply_chain:chokepoints:v1',      600,   'custom', 'Supply chain chokepoints', '{}'),
  ('strategic-posture', '3-59/10 * * * *',     'theater-posture:sebuf:v1',         600,   'custom', 'Strategic theater posture', '{}'),
  ('pizzint',           '4-59/10 * * * *',     'intel:pizzint:v1',                 600,   'custom', 'Pizzint intelligence', '{}'),
  ('iran-events',       '*/10 * * * *',        'conflict:iran-events:v1',          600,   'custom', 'Iran events', '{}'),
  ('weather',           '*/10 * * * *',        'relay:weather:v1',                 600,   'custom', 'Weather data', '{}'),
  ('gps-interference',  '*/5 * * * *',         'relay:gps-interference:v1',        300,   'custom', 'GPS interference data', '{}'),
  ('cables',            '*/15 * * * *',        'relay:cables:v1',                  900,   'custom', 'Undersea cables data', '{}'),
  ('cyber',             '5-59/10 * * * *',     'relay:cyber:v1',                   600,   'custom', 'Cyber threats', '{}'),
  ('service-status',    '*/5 * * * *',         'relay:service-status:v1',          300,   'custom', 'Service status', '{}'),
  ('trade',             '*/15 * * * *',        'relay:trade:v1',                   900,   'custom', 'Trade data', '{}'),
  ('fred',              '*/30 * * * *',        'relay:fred:v1',                    1800,  'custom', 'FRED economic data', '{}'),
  ('oil',               '1-59/30 * * * *',     'relay:oil:v1',                     1800,  'custom', 'Oil data', '{}'),
  ('conflict',          '*/30 * * * *',        'relay:conflict:v1',                1800,  'custom', 'Conflict data', '{}'),
  ('natural',           '2-59/30 * * * *',     'relay:natural:v1',                 1800,  'custom', 'Natural events', '{}'),
  ('eonet',             '*/30 * * * *',        'relay:eonet:v1',                   1800,  'custom', 'EONET natural events', '{}'),
  ('gdacs',             '*/30 * * * *',        'relay:gdacs:v1',                   1800,  'custom', 'GDACS disaster alerts', '{}'),
  ('oref',              '*/5 * * * *',         'relay:oref:v1',                    300,   'custom', 'Israel OREF alerts', '{}'),
  ('opensky',           '*/1 * * * *',         'relay:opensky:v1',                 60,   'custom', 'OpenSky flight data', '{}'),
  ('gdelt',             '*/15 * * * *',        'relay:gdelt:v1',                   900,   'custom', 'GDELT event data', '{}'),
  ('youtube-live',      '*/5 * * * *',         'relay:youtube-live:v1',            300,   'custom', 'YouTube live streams', '{}'),
  ('bis',               '0 * * * *',           'relay:bis:v1',                     3600,  'custom', 'BIS data', '{}'),
  ('flights',           '5 * * * *',           'relay:flights:v1',                 3600,  'custom', 'Flight data', '{}'),
  ('aviation-precache', '0 0 * * *',           '',                                86400, 'custom', 'Aviation precache', '{}'),
  ('giving',            '0 0 * * *',           'giving:summary:v1',                  86400, 'custom', 'Giving summary', '{}'),
  ('climate',           '0 */6 * * *',         'relay:climate:v1',                 21600, 'custom', 'Climate data', '{}'),
  ('ucdp-events',       '0 */6 * * *',         'conflict:ucdp-events:v1',          21600, 'custom', 'UCDP conflict events', '{}'),
  ('worldbank',         '0 */6 * * *',         'relay:worldbank:v1',               21600, 'simple_http', 'World Bank data', '{"url": "https://api.worldbank.org/v2/country/all/indicator/NY.GDP.MKTP.CD?format=json&per_page=50", "response_format": "json"}'),
  ('security-advisories','*/30 * * * *',       'relay:security-advisories:v1',     1800,  'simple_rss', 'Security advisories RSS', '{"url": "https://www.cisa.gov/cybersecurity-advisories/all.xml", "response_format": "rss"}'),
  ('gulf-quotes',       '*/10 * * * *',        'relay:gulf-quotes:v1',             600,   'custom', 'Gulf market quotes', '{}'),
  ('tech-events',       '*/10 * * * *',        'relay:tech-events:v1',             600,   'custom', 'Tech events', '{}'),
  ('spending',          '*/10 * * * *',        'relay:spending:v1',                600,   'custom', 'Government spending', '{}'),
  ('config:news-sources','*/5 * * * *',        'relay:config:news-sources',        300,   'custom', 'News source configuration', '{}'),
  ('config:feature-flags','*/5 * * * *',       'relay:config:feature-flags',       300,   'custom', 'Feature flags configuration', '{}'),
  ('ai:intel-digest',   '*/10 * * * *',        'ai:digest:global:v1',              600,   'custom', 'AI intel digest', '{}'),
  ('ai:panel-summary',  '*/15 * * * *',        'ai:panel-summary:v1',              900,   'custom', 'AI panel summary', '{}'),
  ('ai:article-summaries','2-59/5 * * * *',    'ai:article-summaries:v1',           300,   'custom', 'AI article summaries', '{}'),
  ('ai:country-briefs', '*/30 * * * *',        'ai:country-briefs:v1',          1800,  'custom', 'AI country briefs', '{}'),
  ('ai:posture-analysis','3-59/15 * * * *',    'ai:posture-analysis:v1',           900,   'custom', 'AI posture analysis', '{}'),
  ('ai:instability-analysis','5-59/30 * * * *','ai:instability-analysis:v1',       1800,  'custom', 'AI instability analysis', '{}'),
  ('ai:risk-overview',  '4-59/15 * * * *',     'ai:risk-overview:v1',              900,   'custom', 'AI risk overview', '{}')
ON CONFLICT (service_key) DO NOTHING;
